### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by slackmoehrle** [nahiyan/darwin#1] opened 2020-12-23 21:40 UTC
Hello, 

I am the Community Evangelist for Cocos. We are always interested in seeing how Cocos is being used and what developers are coming up with for projects? Do you have any screenshots of this project? Perhaps we can add this project to some upcoming story by our marketing team.

Thanks!

**Comment by nahiyan** [comment] 2020-12-24 04:10
Hello SlackMoehrle,

Glad to see your interest in my project, Darwin. I'm using the C++ version of Cocos, cocos2d-x, for this project, primary for simulating evolution. Darwin is technically an evolution framework and simulator, extensible by design. I've only worked on it for a few months. You can see screenshots of some of the extensions and interfaces below:

Control Panel (based on wxWidgets):
![Screen Shot 2020-12-24 at 9 57 07 AM](https://user-images.githubusercontent.com/1883545/103059558-a4c73e80-45cf-11eb-96a0-13d05b0de020.png)

Flappy Birds Evolution (cocos2d-x):
![Screen Shot 2020-12-24 at 9 57 35 AM](https://user-images.githubusercontent.com/1883545/103059606-cb857500-45cf-11eb-9f9e-90f9de2b524a.png)

Self-driving Car Evolution (cocos2d-x):
![Screen Shot 2020-12-24 at 9 57 22 AM](https://user-images.githubusercontent.com/1883545/103059588-b9a3d200-45cf-11eb-8ee6-ac2bcaee825d.png)

Jumpers Evolution, with Parallel-Testing (cocos2d-x):
![Screen Shot 2020-12-24 at 9 57 51 AM](https://user-images.githubusercontent.com/1883545/103059648-e9eb7080-45cf-11eb-875d-8526608e30dc.png)

Glad to be a part of the Cocos community!

**Comment by nahiyan** [comment] 2020-12-27 10:34
Since I believe that I provided what you wanted, I'm going to close this. If you have any further query, feel free to ask here.

**Closed by nahiyan** 2020-12-27 10:34 UTC
